export const GUESS_CARD = "Guess 🧐";
export const CHALLENGE_CARD = "Challenge 😉";
export const INDEXES_KEY = "possibleIndexes";
export const PLAYERS_KEY = "players";

export const GUESS_LIST: string[] = [
  "What is the one thing I would save from my burning house?",
  "What excuse do I use most often to avoid going to events?",
  "What is my least favorite household chore?",
  "If I could get rid of one of your belongings what would it be?",
  "Where is my happy place?",
  "If I came with a warning label what would it say?",
  "Which celebrity would I want to play me in a movie about my life?",
  "What was my least favorite subject in school?",
  "What is one thing I wish you did more of?",
  "What dog breed best embodies me?",
  "What is my spirit animal?",
  "Where do I want to go for our next vacation?",
  "What is something that I always forget to do?",
  "What superpower would I want?",
  "How many minutes does it take me to run a mile?",
  "If I could commit one crime and get away with it what would it be?",
  "Name all cities or towns that I have ever lived in.",
  "Who is the one person that I would never want to see naked?",
  "What do I buy too much of?",
  "What topic do I know more about than 90% of people?",
  "Which one of my relatives am I closest to outside of my immediate family?",
  "What object is most sentimental to me?",
  "What's my favorite color?",
  "When's my birthday?",
  "What do I want my life to look like in five years?",
  "Where do I see myself living in an ideal world?",
  "Would I ever relocate to accommodate your job?",
  "What is my favorite food?",
  "What do you like most that I do in bed?",
  "Would I rather use whip cream or hot fudge?",
  "What do I think is my best physical feature?",
  "If I could be on any reality TV show, which one would it be?",
  "Am I a dog person or a cat person?",
  "Who is my best friend?",
  "Do I have any allergies?",
  "Do I have any superstition or belief?",
  "Which is my favorite movie?",
  "What do I normally do in my free time?",
  "Which is my zodiac sign?",
  "Which is my favorite sport?",
  "What is my shoe size?",
  "What day did we meet for the first time?",
  "If I were in a witness protection program, what would my nickname be?",
  "If I could resurrect a famous person, who would I choose?",
  "If I could lock up a person in a madhouse, who would I pick?",
  "If I could travel back in time where would I go?",
  "What would I like to spend more time on?",
  "If I could be a superhero, what would I choose?",
  "What is my unaccomplished sexual fantasy!",
  "Which is my favorite fictional character?",
  "How do I like to relax?",
  "What is my favorite chips flavor?",
  "What is the nicest thing anyone has ever done for me?",
  "What do I like to drink when I go out at night?",
  "What is the first thing I do in the morning when I wake up?",
  "What is the last thing I do before falling asleep at the end of the day?",
  "Which unconscious gesture reveals that I feel uncomfortable with the situation or conversation?",
  "What do I love that I would NEVER admit in public?",
  "Do I normally finish things as soon as possible or do I leave them for the last minute?",
  "What is one of my fears?",
  "What is one of my dreams?",
  "Which do I think about most, past, present or future?",
  "How would I describe myself?",
  "What is my idea of a romantic first date?",
  "Do I have any birthmarks? If so, where?",
  "Do you remember the first words I said to you?",
  "What are my pet peeves?",
  "What are the tells when I lie?",
  "When shouldn’t you talk to me?",
  "What do I identify as my worst habit?",
  "What am I most proud of?",
  "What am I insecure about?",
  "What is my fondest memory as a child?",
  "What are my short-term goals?",
  "What are my long-term goals?",
  "What are the little things that make me happy?",
  "When do you think I first fell in love with you?",
  "Am I likely to tell you if I farted?",
  "What body part turns me on most?",
  "What is my biggest turn off?",
  "What's my favorite thing we've done together?",
  "What is on my sexual bucket list?",
  "What do I need to work on?",
  "What's my spice tolerance on a level of 1 (weak) - 5 (hell fire flames)?",
  "What would I do with 3 extra hours in a day?",
  "If I could immediately master any skill in the world, what would it be?",
  "What am I most looking forward to in 10 years?",
  "What is the one thing I refuse to eat?",
  "What is one adventurous thing I want us to do as a couple?",
  "What am I always craving?",
  "What do I consider to be my greatest flaw?",
  "Which cartoon character would I want to hang out with?",
  "What app do I use the most?",
  "What game have I spent the most time playing?",
  "What do I wish I was better at?",
  "What do I love most about our relationship?",
  "Where are my parents from?",
  "If I had a spare room in the house, what would I use it for?",
  "What country do I want to visit the most?",
  "What is my dream job?",
  "If I had to survive in the wilderness with 1 other person for a week who would it be?",
];

export const CHALLENGE_LIST: string[] = [
  "You have 8 seconds to say the names of 5 of my relatives.",
  "Close your eyes and let me give you something to smell. You have one try to correctly guess what it is.",
  "Let me put lipstick on you.",
  "Text 'I got the results, my butt is fine' to anyone I choose from your contact list.",
  "You have 8 seconds to name 2 countries starting with the letter of my choice (excluding O, Q, and Y).",
  "Close your eyes and let me put something in your mouth. You have one try to correctly guess what it is.",
  "Let me tickle your foot for 30 seconds without resistance!",
  "Quickly spin around in place for 30 seconds, the go and touch something in the room of my choice without falling.",
  "Hold water in your mouth as I read you 3 dad jokes. Do not laugh or spit out any water.",
  "Close your eyes and let me put your finger on any part of my body. You have one try to correctly guess the body part.",
  "Let me run an ice cube across your body until it completely melts",
  "Let me sit on your lap for two minutes",
  "Go outside and loudly mimic the sounds of any animal of my choice for 20 seconds",
  "Call whomever I choose from your contact list and act as if they called you.",
  "Close your eyes and let me put anything in your hand, you have one try to correctly guess what it is.",
  "Give me a piggy back ride around the room.",
  "Let me give you a wet willy.",
  "Serenade me with any song for 60 seconds.",
  "Let me post anything I want on your most used social media account.",
  "Do a pole dance for 30 seconds, using me as a pole.",
  "Sniff the inside of my shoe and rate the smell from 1-10.",
  "Get down on one knee and propose to me with a joke.",
  "Say I love you while doing 50 jumping jacks.",
  "Plank for 30 seconds and while doing it say one thing you love about me.",
  "Give me a relaxing foot massage.",
  "Express your love in sign language.",
  "Belly dance with something from the kitchen as a prop.",
  "Send me the dirtiest text with only emojis you can think of.",
  "Walk around the room and your hands and knees pretending to be a dog.",
  "Kiss your partners big toe.",
  "Act out a scene from your favorite show/movie and let your partner try to guess what it is.",
  "Give your partner a back massage.",
  "Lick your partners face.",
  "Kiss your partner like you were in a romantic comedy",
  "Kiss your partner’s bare booty cheek",
  "Let me feed you something, and be as seductive as possible when eating it.",
  "Take off your shirt for the rest of the game.",
  "Let me choose an embarrassing photo of you to post on your social media account.",
];
