name: Test and deploy

on: push

jobs:
  cypress-and-jest-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NEXTAUTH_JWT_SECRET: "shhhhhhh-this-is-the-testing-secret"
      NEXTAUTH_URL: "http://localhost:3000"
      CYPRESS_NEXTAUTH_JWT_SECRET: "shhhhhhh-this-is-the-testing-secret"
      DEFAULT_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      ENVIRONMENT: "test"
    services:
      localstack:
        image: localstack/localstack:0.14.0
        env:
          SERVICES: dynamodb,sts,s3,iam
        ports:
          - 4566:4566
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Deploy test infra
        run: "make github-deploy-env"
        working-directory: "./infra/life_in_weeks"
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        id: cypress-run
        uses: cypress-io/github-action@v2
        with:
          working-directory: "./my_site"
          build: npm run build
          start: npm start
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Jest run
        run: npm run test:jest
        working-directory: "./my_site"

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: cypress-and-jest-run
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    env:
      ENVIRONMENT: "${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Deploy infra
        run: "make github-deploy-env"
        working-directory: "./infra/life_in_weeks"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-2"
