name: Cypress and Jest tests

on:
  push:
    paths:
      - "my_site/**"

jobs:
  cypress-and-jest-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: "./my_site"
          build: npm run build
          start: npm start
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Jest run
        run: npm run test:jest
        working-directory: "./my_site"
